# Generated by Django 2.1.2 on 2018-11-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('decks', models.IntegerField()),
                ('blackjack_payout', models.FloatField()),
                ('hits_soft_17', models.BooleanField()),
                ('allow_surrender', models.BooleanField()),
                ('max_resplits', models.IntegerField()),
                ('allow_resplit_aces', models.BooleanField()),
                ('allow_double_after_split', models.BooleanField()),
                ('allow_insurance', models.BooleanField()),
                ('dealer_wins_ties', models.BooleanField()),
            ],
        ),
    ]
