# Generated by Django 2.1.2 on 2018-11-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='allow_double_after_split',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='allow_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='allow_resplit_aces',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='allow_surrender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='blackjack_payout',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='dealer_wins_ties',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='decks',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='hits_soft_17',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='max_resplits',
            field=models.IntegerField(default=1),
        ),
    ]
